apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: note-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-db
  template:
    metadata:
      labels:
        app: note-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
          - name: POSTGRES_DB
            value: notes_db
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: note-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: note-db
spec:
  ports:
    - port: 5432
  selector:
    app: note-db
